name: elkhlod
description: الخلود للمقاولات العمومية
publish_to: "none"
version: 0.0.8+8
environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_bloc: ^8.1.5
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_localization: ^0.2.0
  introduction_screen: ^3.1.14
  fluttertoast: ^8.2.8
  flutter_spinkit: ^5.2.1
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  animated_bottom_navigation_bar: ^1.3.3
  intl: ^0.20.0
  flutter_svg: ^2.0.10+1
  flutter_verification_code: ^1.1.7
  dotted_line: ^3.1.0
  tab_container: ^2.0.0
  flutter_switch: ^0.3.2
  toggle_switch: ^2.1.0
  im_stepper: ^1.0.1+1
  animate_do: ^3.3.4
  equatable: ^2.0.5
  connectivity_plus: ^6.0.5
  cached_network_image: ^3.4.1
  device_preview: ^1.2.0
  logger: ^2.4.0
  sprintf: ^7.0.0
  get: ^4.6.6
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  table_calendar: ^3.1.2
  dropdown_search: ^6.0.1
  pin_code_fields: ^8.0.1
  wakelock_plus: ^1.2.8
  file_picker: ^8.1.2
  http: ^1.2.2
  flutter_rating_bar: ^4.0.1
  month_picker_dialog: ^5.1.2
  open_file: ^3.5.9
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  syncfusion_flutter_pdfviewer: ^31.2.12
  image_picker: ^1.1.2
  scribble: ^0.10.0
  custom_rating_bar: ^3.0.0
  share_plus: ^10.0.2
  percent_indicator: ^4.2.3
  pdf: ^3.11.1
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0
  confetti: ^0.8.0
  shared_preferences: ^2.3.2

  google_mlkit_face_detection: ^0.12.0  # downgrade للمتوافق مع Firebase 10.25.0 و GoogleDataTransport ~> 9.4
  google_mlkit_commons: ^0.9.0

  firebase_core: 3.14.0  # يبقى كما هو (دون ^)
  firebase_messaging: 15.2.7
  flutter_local_notifications: ^17.2.2
  face_camera: ^0.1.4
  flutter_state_notifier: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - lang/en.json
    - lang/ar.json
  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
    - family: Hacen Tunisia
      fonts:
        - asset: assets/fonts/Hacen Tunisia.ttf
    - family: Cairo-Regular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Cairo-Bold
      fonts:
        - asset: assets/fonts/Cairo-Bold-3.ttf
    - family: new-font
      fonts:
        - asset: assets/fonts/new_font.ttf